; https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html
((nil . ((create-lockfiles . nil)
	 ))
 (js-mode . ((create-lockfiles . nil)
             ))
 (js2-mode . ((create-lockfiles . nil)
              ))
 (rjsx-mode . ((create-lockfiles . nil)
               ))
 (web-mode . ((create-lockfiles . nil)
              ))
 )
